#Use the following metricPrefix if SIM is enabled.
#metricPrefix: "Custom Metrics|AWS APIGateway"
#Use the following metricPrefix if SIM is not enabled.
metricPrefix: "Server|Component:<COMPONENT_ID>|Custom Metrics|AWS APIGateway"

#Allowed values are Basic and Detailed. Refer https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-cloudwatch-new.html for more information
# Basic will fire CloudWatch API calls every 5 minutes
# Detailed will fire CloudWatch API calls every 1 minutes
cloudWatchMonitoring: "Basic"
#If you want to run the extension with a further delay, comment the "cloudWatchMonitoring" and use the following field
#which takes in the number of minutes after which th extension should call the cloudwatch metrics
#cloudWatchMonitoringInterval:10

concurrencyConfig:
  noOfAccountThreads: 3
  noOfRegionThreadsPerAccount: 3
  noOfMetricThreadsPerRegion: 3
  #Thread timeout in seconds
  threadTimeOut: 30


#Allowed values for "regions" : ap-northeast-1, ap-southeast-1, ap-southeast-2, eu-central-1, us-east-1, us-west-1, us-west-2, eu-west-1, sa-east-1
accounts:
  - awsAccessKey: ""
    awsSecretKey: ""
    displayAccountName: "AppD"
    regions: ["us-east-1"]


metricsConfig:
    # Global time range configuration, applicable to all the metrics configured below.
    metricsTimeRange:
        startTimeInMinsBeforeNow: 10
        endTimeInMinsBeforeNow: 0
    # Rate limit ( per second ) for GetMetricStatistics, default value is 400. https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_limits.html
    getMetricStatisticsRateLimit: 400
    # The max number of retry attempts for failed retryable requests
    # (ex: 5xx error responses from a service) or throttling errors
    maxErrorRetrySize: 0
    # By default, all metrics retrieved from cloudwatch are 'Average' values.
    # This option allows you to override the metric type.
    # Allowed statTypes are: ave, max, min, sum, samplecount
    # Note: Irrespective of the metric type, value will still be reported as
    # Observed value to the Controller
    # Time range configuration to individual metrics also supported. If not configured uses the global time range configuration
    #    metricsTimeRange:
    #       startTimeInMinsBeforeNow: 15
    #       endTimeInMinsBeforeNow: 0
    includeMetrics:
        - name: ""
          alias: ""
          statType: ""
          delta: ""
          multiplier:
          aggregationType: ""
          timeRollUpType: ""
          clusterRollUpType: ""
          metricsTimeRange:
              startTimeInMinsBeforeNow: 10
              endTimeInMinsBeforeNow: 0





regionEndPoints:
  ap-northeast-1: monitoring.ap-northeast-1.amazonaws.com
  ap-southeast-1: monitoring.ap-southeast-1.amazonaws.com
  ap-southeast-2: monitoring.ap-southeast-2.amazonaws.com
  eu-central-1: monitoring.eu-central-1.amazonaws.com
  us-east-1: monitoring.us-east-1.amazonaws.com
  us-west-1: monitoring.us-west-1.amazonaws.com
  us-west-2: monitoring.us-west-2.amazonaws.com
  eu-west-1: monitoring.eu-west-1.amazonaws.com
  sa-east-1: monitoring.sa-east-1.amazonaws.com

